name: tree_sitter
description: A tree sitter parsing library
version: 0.1.1
repository: https://github.com/UserNobody14/tree-sitter-dart

environment:
  sdk: ">=3.0.0 <3.2.0"

dependencies:
  dylib: ^0.3.3
  args: ^2.4.1
  ffi: ^2.0.1
  freezed_annotation: ^2.2.0
  path: ^1.8.3
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
  ffigen: ^8.0.2
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  build_runner: ^2.4.4

executables:
  tsdart: gen_grammar  