name: Release

on:
  push:
    tags:
      - "[0-9]+.*"

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # Create a draft release so we can add the changelog before publishing it
          # so the changelog is included in the release email
          draft: true
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Targets that match the OS of the runner.
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-apple-darwin
            os: macos-latest

          # Targets using cross-compilation (upload-rust-binary-action
          # detects that they need cross).
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
          - target: wasm32-wasip1
            os: ubuntu-24.04
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: aarch64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      # v4.2.2
      - run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-29/wasi-sdk-29.0-x86_64-linux.deb
          sudo apt-get install ./wasi-sdk-29.0-x86_64-linux.deb
          rm ./wasi-sdk-29.0-x86_64-linux.deb
          rustup override set stable
          rustup target add wasm32-wasip1
        if: ${{ matrix.target == 'wasm32-wasip1' }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: difft
          # (optional) On which platform to distribute the `.tar.gz` file.
          tar: unix
          # (optional) On which platform to distribute the `.zip` file.
          zip: windows
          # (optional) Target triple, default is host triple.
          target: ${{ matrix.target }}
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WASI_SDK_PATH: /opt/wasi-sdk
          WASI_SYSROOT: /opt/wasi-sdk/share/wasi-sysroot
          CC_wasm32_wasip1: /opt/wasi-sdk/bin/clang
          AR_wasm32_wasip1: /opt/wasi-sdk/bin/llvm-ar
          CFLAGS_wasm32_wasip1: "--sysroot=/opt/wasi-sdk/share/wasi-sysroot"

  push_crates_io:
    runs-on: ubuntu-22.04
    steps:
      # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
