on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: ğŸ¦€  Build and Test rust bindings

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      
      - name: ğŸ“¥ Download the repository
        uses: actions/checkout@v2
      - name: ğŸ¦€ Install rust 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: ğŸ“¥  Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: ğŸ“¥  Install js dependencies
        run: |
          npm install yarn
          npm install tree-sitter-cli -g

      - name: ğŸŒ² Generate the parser
        run: tree-sitter generate

      - name: ğŸ›  Build rust bindings
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      # Run the tests
      - name: ğŸ§ª Now run the rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test